Starting with CRUD
mludeiro/training-go-invoices pull request #4
Opened 2021-12-23 15:31 UTC by bpilegi98

This is just a commit of the basic CRUD so Carlos can start working on the handler 😄

2021-12-23 17:36 UTC, pabloamura requested changes

2021-12-23 17:36 UTC, pabloamura commented on entity/product.go
>  type Product struct {
En realidad en el microservicio de invoices, deberia haber una entidad de invoice, con Id del producto, pero no una tabla (en principio) de productos, sino que cuandos se necesita algun dato del producto, se consume el microservicio de productos. Hagamos ese cambio y despues en todo caso, en otra version, podemos modificarlo por cuestiones de performance, pero en principio el approach microservicio sería asi me parece

2021-12-23 19:00 UTC, pabloamura requested changes

2021-12-23 19:00 UTC, pabloamura commented on entity/invoice.go
> +	Products    []uint    `json:",omitempty"`
Add invoice items or invoice details

2021-12-28 14:11 UTC, mludeiro requested changes
//Is this ok?
var db = &gorm.DB{}
 
No, you should use the DB defined in the container. Maybe by injection (creating a repository object). A simpler way is to use a singleton, for the db or the container that has the db associated
Please check out the container definition in go-micro

2021-12-28 14:11 UTC, mludeiro commented on repository/invoice.go
> +var db = &gorm.DB{}
No, you should use the DB already declared in the container. Maybe by injection (creating a repository object). A simpler way is to use a singleton, preferably for the container that has the db associated
Please check out the container definition in go-micro, or we can have a meet to clarify

2021-12-29 21:06 UTC, mludeiro approved these changes

2021-12-30 18:38 UTC, merged